# -*- coding: utf-8 -*-
"""공공데이터 이미지 크롤링

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1f-px0mkjNZq_HNZr5vl1oIPB6oNNOEnT
"""

from google.colab import drive
drive.mount('/content/drive')

import urllib.request
from bs4 import BeautifulSoup

#처음 페이지로 접근할 번호
pagenum = 1
#저장할 이미지 경로와 이름(image 폴더에 img.jpg로 저장)
imagenum = 0
imagestr = "/content/drive/MyDrive/Colab Notebooks/image/img"

while pagenum < 5:
  url = "https://www.ito.or.kr/main/bbs/bbsMsgList.do?cate1=02&bcd=galleryko&pgno="
  url = url + str(pagenum)

  fp = urllib.request.urlopen(url)
  source = fp.read();
  fp.close()

  soup = BeautifulSoup(source, 'html.parser')
  soup = soup.findAll("p",class_ = "img")

  # 이미지 경로를 받아서 저장하기
  for i in soup:
    imagenum += 1
    imgurl = "https://www.ito.or.kr/"+i.find("img")["src"]
    urllib.request.urlretrieve(imgurl,imagestr + str(imagenum) +".jpg")
    print(imgurl)
    print(imagenum)

  pagenum += 1